### PR TITLE
use chess in peripherial to simplify api for app layer

### PR DESCRIPTION
**Pull request by dkwach**

### CODE REVIEW

**Comment by mono424** [comment]
On first view this looks super nice! I see the point that it makes it a "Batteries-Included" package.
Nevertheless I am scared this could create inconsistencies between an app game state and the peripheral state. There are then two sources of truth. Also not giving the app developer the power to apply his own chess rules may be kind of to restricting, what do you think?

**Comment by dkwach** [comment]
> "Batteries-Included"

I reverted onMoveJudgement removal. Different idea:
How about having some contract class passed in UniversalPeripheral constructor:
```
UniversalPeripheral(AppContract contract)
```

where AppContract would be small helper class with interface:
```
abstract class AppContract {
  bool isMoveLegal(String uci);
}
```

**Comment by mono424** [comment]
Love that idea, makes it way more flexible but also easy to use on my opinion :))

**Comment by dkwach** [comment]
> Love that idea, makes it way more flexible but also easy to use on my opinion :))

Done with new commit.

**Pull request merged**
